name: Terraform CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AAKIA4DU5VRRQ46JUHG2Z }}
        aws-secret-access-key: ${{ secrets.AGmS1TnkDTpvR44B7z8MRYSypxEYOKZVuFGTKIH3P }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    # Uncomment to enable automatic apply
    # - name: Terraform Apply
    #   run: terraform apply -auto-approve
